services:
  - type: web
    name: travsify-ndc
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        value: "https://dprdpztanrxnwvgsowoz.supabase.co"
      - key: SUPABASE_PUBLISHABLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcmRwenRhbnJ4bnd2Z3Nvd296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMzA2NDYsImV4cCI6MjA5MjYwNjY0Nn0.nbzKcXu5ZRIGezRbjttmPID1uSy7wYN5FjCJGbOXGkg"
      - key: VITE_SUPABASE_URL
        value: "https://dprdpztanrxnwvgsowoz.supabase.co"
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcmRwenRhbnJ4bnd2Z3Nvd296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMzA2NDYsImV4cCI6MjA5MjYwNjY0Nn0.nbzKcXu5ZRIGezRbjttmPID1uSy7wYN5FjCJGbOXGkg"
      - key: VITE_SUPABASE_PROJECT_ID
        value: "dprdpztanrxnwvgsowoz"
      - key: FIRECRAWL_API_KEY
        value: "your-firecrawl-api-key"
