services:
  - type: web
    name: travsify-ndc
    runtime: node
    plan: free
    buildCommand: npm install --no-package-lock && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: SUPABASE_URL
        value: "https://dprdpztanrxnwvgsowoz.supabase.co"
      - key: SUPABASE_PUBLISHABLE_KEY
        value: "sb_publishable_zA0SI1W8r0WEKUrNZGuQBg_MmIv5Ruc"
      - key: SUPABASE_ANON_KEY
        value: "sb_publishable_zA0SI1W8r0WEKUrNZGuQBg_MmIv5Ruc"
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        value: "https://dprdpztanrxnwvgsowoz.supabase.co"
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: "sb_publishable_zA0SI1W8r0WEKUrNZGuQBg_MmIv5Ruc"
      - key: VITE_SUPABASE_PROJECT_ID
        value: "dprdpztanrxnwvgsowoz"
      - key: FIRECRAWL_API_KEY
        value: "your-firecrawl-api-key"
