/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GetApiAccessRouteImport } from './routes/get-api-access'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SdkJsRouteImport } from './routes/sdk.js'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedPendingReviewRouteImport } from './routes/_authenticated/pending-review'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiV1PayoutsRouteImport } from './routes/api/v1/payouts'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiPublicDemoSearchRouteImport } from './routes/api/public/demo-search'
import { Route as ApiV1PaymentsIntentsRouteImport } from './routes/api/v1/payments.intents'
import { Route as ApiV1HotelsSearchRouteImport } from './routes/api/v1/hotels.search'
import { Route as ApiV1HotelsBookingsRouteImport } from './routes/api/v1/hotels.bookings'
import { Route as ApiV1FlightsSearchRouteImport } from './routes/api/v1/flights.search'
import { Route as ApiV1FlightsOrdersRouteImport } from './routes/api/v1/flights.orders'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks.stripe'
import { Route as ApiPublicWebhooksFincraRouteImport } from './routes/api/public/webhooks.fincra'
import { Route as AuthenticatedAdminApplicationsIdRouteImport } from './routes/_authenticated/admin/applications.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetApiAccessRoute = GetApiAccessRouteImport.update({
  id: '/get-api-access',
  path: '/get-api-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkJsRoute = SdkJsRouteImport.update({
  id: '/sdk/js',
  path: '/sdk/js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingReviewRoute =
  AuthenticatedPendingReviewRouteImport.update({
    id: '/pending-review',
    path: '/pending-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiV1PayoutsRoute = ApiV1PayoutsRouteImport.update({
  id: '/api/v1/payouts',
  path: '/api/v1/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDemoSearchRoute = ApiPublicDemoSearchRouteImport.update({
  id: '/api/public/demo-search',
  path: '/api/public/demo-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PaymentsIntentsRoute = ApiV1PaymentsIntentsRouteImport.update({
  id: '/api/v1/payments/intents',
  path: '/api/v1/payments/intents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HotelsSearchRoute = ApiV1HotelsSearchRouteImport.update({
  id: '/api/v1/hotels/search',
  path: '/api/v1/hotels/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HotelsBookingsRoute = ApiV1HotelsBookingsRouteImport.update({
  id: '/api/v1/hotels/bookings',
  path: '/api/v1/hotels/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FlightsSearchRoute = ApiV1FlightsSearchRouteImport.update({
  id: '/api/v1/flights/search',
  path: '/api/v1/flights/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FlightsOrdersRoute = ApiV1FlightsOrdersRouteImport.update({
  id: '/api/v1/flights/orders',
  path: '/api/v1/flights/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksFincraRoute = ApiPublicWebhooksFincraRouteImport.update({
  id: '/api/public/webhooks/fincra',
  path: '/api/public/webhooks/fincra',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminApplicationsIdRoute =
  AuthenticatedAdminApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/get-api-access': typeof GetApiAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/pending-review': typeof AuthenticatedPendingReviewRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/sdk/js': typeof SdkJsRoute
  '/api/public/demo-search': typeof ApiPublicDemoSearchRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/api/public/webhooks/fincra': typeof ApiPublicWebhooksFincraRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/v1/flights/orders': typeof ApiV1FlightsOrdersRoute
  '/api/v1/flights/search': typeof ApiV1FlightsSearchRoute
  '/api/v1/hotels/bookings': typeof ApiV1HotelsBookingsRoute
  '/api/v1/hotels/search': typeof ApiV1HotelsSearchRoute
  '/api/v1/payments/intents': typeof ApiV1PaymentsIntentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/get-api-access': typeof GetApiAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/pending-review': typeof AuthenticatedPendingReviewRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/sdk/js': typeof SdkJsRoute
  '/api/public/demo-search': typeof ApiPublicDemoSearchRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/api/public/webhooks/fincra': typeof ApiPublicWebhooksFincraRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/v1/flights/orders': typeof ApiV1FlightsOrdersRoute
  '/api/v1/flights/search': typeof ApiV1FlightsSearchRoute
  '/api/v1/hotels/bookings': typeof ApiV1HotelsBookingsRoute
  '/api/v1/hotels/search': typeof ApiV1HotelsSearchRoute
  '/api/v1/payments/intents': typeof ApiV1PaymentsIntentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/get-api-access': typeof GetApiAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/pending-review': typeof AuthenticatedPendingReviewRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/sdk/js': typeof SdkJsRoute
  '/api/public/demo-search': typeof ApiPublicDemoSearchRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/payouts': typeof ApiV1PayoutsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/applications/$id': typeof AuthenticatedAdminApplicationsIdRoute
  '/api/public/webhooks/fincra': typeof ApiPublicWebhooksFincraRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/v1/flights/orders': typeof ApiV1FlightsOrdersRoute
  '/api/v1/flights/search': typeof ApiV1FlightsSearchRoute
  '/api/v1/hotels/bookings': typeof ApiV1HotelsBookingsRoute
  '/api/v1/hotels/search': typeof ApiV1HotelsSearchRoute
  '/api/v1/payments/intents': typeof ApiV1PaymentsIntentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/demo'
    | '/developers'
    | '/docs'
    | '/get-api-access'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/kyc'
    | '/pending-review'
    | '/wallet'
    | '/sdk/js'
    | '/api/public/demo-search'
    | '/api/v1/health'
    | '/api/v1/payouts'
    | '/admin/'
    | '/admin/applications/$id'
    | '/api/public/webhooks/fincra'
    | '/api/public/webhooks/stripe'
    | '/api/v1/flights/orders'
    | '/api/v1/flights/search'
    | '/api/v1/hotels/bookings'
    | '/api/v1/hotels/search'
    | '/api/v1/payments/intents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/demo'
    | '/developers'
    | '/docs'
    | '/get-api-access'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/kyc'
    | '/pending-review'
    | '/wallet'
    | '/sdk/js'
    | '/api/public/demo-search'
    | '/api/v1/health'
    | '/api/v1/payouts'
    | '/admin'
    | '/admin/applications/$id'
    | '/api/public/webhooks/fincra'
    | '/api/public/webhooks/stripe'
    | '/api/v1/flights/orders'
    | '/api/v1/flights/search'
    | '/api/v1/hotels/bookings'
    | '/api/v1/hotels/search'
    | '/api/v1/payments/intents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/demo'
    | '/developers'
    | '/docs'
    | '/get-api-access'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/kyc'
    | '/_authenticated/pending-review'
    | '/_authenticated/wallet'
    | '/sdk/js'
    | '/api/public/demo-search'
    | '/api/v1/health'
    | '/api/v1/payouts'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/applications/$id'
    | '/api/public/webhooks/fincra'
    | '/api/public/webhooks/stripe'
    | '/api/v1/flights/orders'
    | '/api/v1/flights/search'
    | '/api/v1/hotels/bookings'
    | '/api/v1/hotels/search'
    | '/api/v1/payments/intents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  GetApiAccessRoute: typeof GetApiAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SdkJsRoute: typeof SdkJsRoute
  ApiPublicDemoSearchRoute: typeof ApiPublicDemoSearchRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1PayoutsRoute: typeof ApiV1PayoutsRoute
  ApiPublicWebhooksFincraRoute: typeof ApiPublicWebhooksFincraRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiV1FlightsOrdersRoute: typeof ApiV1FlightsOrdersRoute
  ApiV1FlightsSearchRoute: typeof ApiV1FlightsSearchRoute
  ApiV1HotelsBookingsRoute: typeof ApiV1HotelsBookingsRoute
  ApiV1HotelsSearchRoute: typeof ApiV1HotelsSearchRoute
  ApiV1PaymentsIntentsRoute: typeof ApiV1PaymentsIntentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-api-access': {
      id: '/get-api-access'
      path: '/get-api-access'
      fullPath: '/get-api-access'
      preLoaderRoute: typeof GetApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk/js': {
      id: '/sdk/js'
      path: '/sdk/js'
      fullPath: '/sdk/js'
      preLoaderRoute: typeof SdkJsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending-review': {
      id: '/_authenticated/pending-review'
      path: '/pending-review'
      fullPath: '/pending-review'
      preLoaderRoute: typeof AuthenticatedPendingReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/v1/payouts': {
      id: '/api/v1/payouts'
      path: '/api/v1/payouts'
      fullPath: '/api/v1/payouts'
      preLoaderRoute: typeof ApiV1PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-search': {
      id: '/api/public/demo-search'
      path: '/api/public/demo-search'
      fullPath: '/api/public/demo-search'
      preLoaderRoute: typeof ApiPublicDemoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/payments/intents': {
      id: '/api/v1/payments/intents'
      path: '/api/v1/payments/intents'
      fullPath: '/api/v1/payments/intents'
      preLoaderRoute: typeof ApiV1PaymentsIntentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/hotels/search': {
      id: '/api/v1/hotels/search'
      path: '/api/v1/hotels/search'
      fullPath: '/api/v1/hotels/search'
      preLoaderRoute: typeof ApiV1HotelsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/hotels/bookings': {
      id: '/api/v1/hotels/bookings'
      path: '/api/v1/hotels/bookings'
      fullPath: '/api/v1/hotels/bookings'
      preLoaderRoute: typeof ApiV1HotelsBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/flights/search': {
      id: '/api/v1/flights/search'
      path: '/api/v1/flights/search'
      fullPath: '/api/v1/flights/search'
      preLoaderRoute: typeof ApiV1FlightsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/flights/orders': {
      id: '/api/v1/flights/orders'
      path: '/api/v1/flights/orders'
      fullPath: '/api/v1/flights/orders'
      preLoaderRoute: typeof ApiV1FlightsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/fincra': {
      id: '/api/public/webhooks/fincra'
      path: '/api/public/webhooks/fincra'
      fullPath: '/api/public/webhooks/fincra'
      preLoaderRoute: typeof ApiPublicWebhooksFincraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/applications/$id': {
      id: '/_authenticated/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApplicationsIdRoute: typeof AuthenticatedAdminApplicationsIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApplicationsIdRoute: AuthenticatedAdminApplicationsIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedPendingReviewRoute: typeof AuthenticatedPendingReviewRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedPendingReviewRoute: AuthenticatedPendingReviewRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  GetApiAccessRoute: GetApiAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SdkJsRoute: SdkJsRoute,
  ApiPublicDemoSearchRoute: ApiPublicDemoSearchRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1PayoutsRoute: ApiV1PayoutsRoute,
  ApiPublicWebhooksFincraRoute: ApiPublicWebhooksFincraRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiV1FlightsOrdersRoute: ApiV1FlightsOrdersRoute,
  ApiV1FlightsSearchRoute: ApiV1FlightsSearchRoute,
  ApiV1HotelsBookingsRoute: ApiV1HotelsBookingsRoute,
  ApiV1HotelsSearchRoute: ApiV1HotelsSearchRoute,
  ApiV1PaymentsIntentsRoute: ApiV1PaymentsIntentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
